swagger: "2.0"
info:
  description: '
  Trabalho de Conclusão da Disciplina de SERVICES ARCHITECTURE / API / MOBILE ARCHITECTURE<br><br>
  Case da aplicação Netflix<br><br>
  <b>Grupo:</b><br>
  Bruno Vinicius Cavalcante da Silva - 336968<br>
  Felipe Verissimo Gonzalez - 337283<br>
  Gabriel Muniz de Lima - 337821<br>
  '
  version: "1.0.0"
  title: "TCD - Netflix"
basePath: "/v1"
tags:
  - name: "suporte"
    description: "Relatar problemas que podem estar acontecendo."
  - name: "filmes"
    description: "Parte de filmes"
  - name: "usuario"
    description: "Parte de usuarios"
schemes:
  - "http"
paths:
  /suporte/reportar:
    post:
      tags:
        - "suporte"
      summary: "Cria um novo chamado para a equipe de suporte."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Informações do problema ocorrido"
          required: true
          schema:
            $ref: "#/definitions/Problema"
      responses:
        "200":
          description: "Ok Message"
          schema:
            type: "string"
        "405":
          description: "Invalid input"
definitions:
  Problema:
    type: "object"
    properties:
      idFilme:
        type: "integer"
        format: "int64"
      descricaoErro:
        type: "string"
        description: "Descrição do problema"
      idUsuario:
        type: "integer"
        format: "int64"
        description: "Id do usuário que esta relatando o problema."
      nomeUsuario:
        type: "string"
        description: "Nome do usuário que esta relatando o problema."